import type { Metadata } from 'next';
import { Geist_Mono, Roboto } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import React from 'react';

const roboto = Roboto({
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Personal App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${roboto.className} ${geistMono.variable} antialiased`}>
                <Toaster position="top-right" reverseOrder={false} />
                {children}
            </body>
        </html>
    );
}
